from sessions_component.controllers.login import login
from sessions_component.controllers.logout import logout
from sessions_component.controllers.changepassword import changepassword
from sessions_component.controllers.signup import signup
from sessions_component.controllers.checkpermissions import checkpermissions
from sessions_component.controllers.unregister import unregister
from sessions_component.controllers.process import process